// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hriaxoszdbdwxeahbiwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyaWF4b3N6ZGJkd3hlYWhiaXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDM2MjcsImV4cCI6MjA2NjI3OTYyN30.sANHp1skDsWnagO4x2hJ29cEZoUiTuFxyZxhaoZcz98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);